// // import type { Metadata } from "next";
// // import { Geist, Geist_Mono } from "next/font/google";
// // import "./globals.css";
// // import { cn } from "@/lib/utils";

// // const geistSans = Geist({
// //   variable: "--font-geist-sans",
// //   subsets: ["latin"],
// // });

// // const geistMono = Geist_Mono({
// //   variable: "--font-geist-mono",
// //   subsets: ["latin"],
// // });

// // export const metadata: Metadata = {
// //   title: "Create Next App",
// //   description: "Generated by create next app",
// // };

// // export default function RootLayout({
// //   children,
// // }: Readonly<{
// //   children: React.ReactNode;
// // }>) {
// //   return (
// //     <html lang="en">
// //       <body
// //         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
// //       >
// //         {children}
// //       </body>
// //     </html>
// //   );
// // }












// // import type { Metadata } from "next";
// // import { Geist, Geist_Mono } from "next/font/google";
// // import "./globals.css";
// // import { cn } from "@/lib/utils";
// // import aos from "@/app/aos";


// // const geistSans = Geist({
// //   variable: "--font-geist-sans",
// //   subsets: ["latin"],
// // });

// // const geistMono = Geist_Mono({
// //   variable: "--font-geist-mono",
// //   subsets: ["latin"],
// // });

// // export const metadata: Metadata = {
// //   title: "Create Next App",
// //   description: "Generated by create next app",
// // };

// // export default function RootLayout({
// //   children,
// // }: {
// //   children: React.ReactNode;
// // }) {
// //   return (
// //     <html lang="en" suppressHydrationWarning>
// //       <body
// //         className={cn(
// //           "min-h-screen bg-background font-sans antialiased text-foreground",
// //           geistSans.variable,
// //           geistMono.variable
// //         )}
// //       >
// //         {children}
// //       </body>
// //     </html>
// //   );
// // }





// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";
// import { cn } from "@/lib/utils";
// import AosInit from "@/app/aos";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: {
//   children: React.ReactNode;
// }) {
//   return (
//     <html lang="en" suppressHydrationWarning>
//       <body
//         className={cn(
//           "min-h-screen bg-background font-sans antialiased text-foreground",
//           geistSans.variable,
//           geistMono.variable
//         )}
//       >
//         <AosInit />
//         {children}
//       </body>
//     </html>
//   );
// }





import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Vedanta Keshri - Frontend Developer',
  description: 'Experienced Frontend Developer specializing in Next.js, React.js, and modern web technologies. Creating optimized, responsive web applications.',
  keywords: 'frontend developer, next.js, react.js, web development, javascript, tailwind css',
  authors: [{ name: 'Vedanta Keshri' }],
  openGraph: {
    title: 'Vedanta Keshri - Frontend Developer',
    description: 'Experienced Frontend Developer specializing in Next.js, React.js, and modern web technologies.',
    type: 'website',
    url: 'https://vedantakeshri.dev',
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="scroll-smooth">
      <body className={`${inter.className} bg-gradient-to-br from-slate-900 via-blue-900 to-slate-800 text-white`}>
        {children}
      </body>
    </html>
  );
}
